//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMahasiswaEntities1 : DbContext
    {
        public DBMahasiswaEntities1()
            : base("name=DBMahasiswaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tabel_mahasiswa> tabel_mahasiswa { get; set; }
        public virtual DbSet<tabel_matakuliah> tabel_matakuliah { get; set; }
        public virtual DbSet<tabel_nilai> tabel_nilai { get; set; }
    }
}
